### PR TITLE
ulinux+webcamd: add support Geniatech T220A, usbtv, STK1160, TM6000 based devices

### PR DESCRIPTION
**Pull request by rozhuk-im**
- Geniatech T220A / NXP TDA18273 silicon tuner (from https://github.com/ljalves/linux_media )
- TM6000 based DVB-T & Analog TV USB Stick
- STK1160 based analog video capture
- usbtv dongles

### CODE REVIEW

**Review by hselasky — COMMENTED** [review]
Start the commit message with "ulinux+webcamd:" followed by a description of your changes and I'll merge it.

**Comment by rozhuk-im** [comment]
Should build/config.h  be updated too?

**Comment by hselasky** [comment]
It is usually overwritten when you build webcamd. But if you want, run:

make configure HAVE_ALL_DRV=YES HAVE_COMPAT32=YES

It helps keep track of config options that are added and removed from time to time.

I just made commit updating build/  :-)

**Comment by hselasky** [comment]
https://svnweb.freebsd.org/changeset/ports/556835

**Comment by rozhuk-im** [comment]
Ok, I will leave as is :)
Thanks!

**Pull request merged**
